version: "3.8"
services:
  inference:
    # network_mode: host
    container_name: "semantic-segment-inference2"
    build: "./inference"
    command: "uvicorn main:app --host 0.0.0.0 --port 5553 --reload"
    ports:
      - "5553:5553"
    volumes:
      - ./inference:/code
      - ./volumes/weights:/weights

    environment:
      - PORT=5556
      - WEIGHTS_DIR=/weights
    ipc: host
    shm_size: 1024M
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    networks:
      - segment-network
  #
  train:
    # network_mode: host
    container_name: "semantic-segment-train2"
    build: "./train"
    command: "uvicorn main:app --host 0.0.0.0 --port 5554 --reload"
    ports:
      - "5554:5554"
    volumes:
      - ./train:/code
      - ./volumes/weights:/weights
      - ./volumes/dataset:/dataset
    environment:
      - RESPONSE_URL=http://web:8000/api/v1/train/done
      - LOGGER_URL=http://127.0.0.1:8000/logger
      - PORT=5554
      - IS_LOGGER_ON=False
      - WEIGHTS_DIR=/weights
    ipc: host
    shm_size: 1024M
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu]
    networks:
      - segment-network

  redis:
    restart: always
    image: redis:latest
    expose:
      - "6379"
    volumes:
      - ./volumes/redis-data:/data
    networks:
      - segment-network

networks:
  segment-network:

